from enum import Enum

class SYSTEM_ACTIONS(Enum):
    FILE = 0
    HOME = 1
    QUIT = 2
    MENU = 3
    OPEN = 4
    USER_SETTINGS = 8

class FILE_PREVIEW_ACTIONS(Enum):
    SHOW_3D = 5
    SHOW_2D = 6
    GESTURE_CONTROLS = 7
    ZOOM_IN = 9
    ZOOM_OUT = 10
    FILE_CONTENTS = 11
    FILE_SAVE = 12
    FILE_SAVE_AS = 13
    FILE_PRINT = 14
    FILE_SETTINGS = 15
    FILE_SINGLE_PAGE = 16
    FILE_DOUBLE_PAGE = 17
    FIT_TO_WINDOW = 18
    FIT_TO_WIDTH = 19
    FILE_PAGE = 20
    NEXT_PAGE = 21
    PREVIOUS_PAGE = 22